### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by aaronmelton** [aaronmelton/VRFSearchAndBackup#1]
Application fails when pulling configuration from Cisco IOS 15.2:
## VRFSearchAndBackup.py v1.0.1 (2014-03-17)

--> Index found and appears up to date.

Enter the VRF Name or IP Address you are searching for: ABC-12345

+--------------------+--------------------+--------------------+
|      VRF NAME      | REMOTE IP ADDRESS  |  LOCAL IP ADDRESS  |
+--------------------+--------------------+--------------------+
|     ABC-12345      |    192.168.1.1     |   192.168.2.1      |
|     ABC-12345      |    192.168.1.1     |   192.168.2.1      |
+--------------------+--------------------+--------------------+

Do you want to back up this configuration now? [Y/n]

--> Logging into 192.168.2.1...
--> Backing up ABC-12345 ...
Traceback (most recent call last):
  File "<string>", line 534, in <module>
  File "<string>", line 413, in searchIndex
  File "<string>", line 176, in backupVRF
AttributeError: 'NoneType' object has no attribute 'group'

C:\Applications>

**Comment by aaronmelton** [comment]
Discovered the application was placing a trailing space from the user input into the vrfName variable. This was causing the router to return results that did not include the Route Descriptor thereby causing the following REGEX statement to not find any matches and the backup function fails.

Unknown why older versions of Cisco IOS did not suffer from this error but will push an update to this code.
